apiVersion: v1
kind: Service
metadata:
  name: alien
  labels:
    app: alien
spec:
  type: ClusterIP
  selector:
    app: alien
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
