export const browserCoreExamples = [
  "alien browser status",
  "alien browser start",
  "alien browser start --headless",
  "alien browser stop",
  "alien browser tabs",
  "alien browser open https://example.com",
  "alien browser focus abcd1234",
  "alien browser close abcd1234",
  "alien browser screenshot",
  "alien browser screenshot --full-page",
  "alien browser screenshot --ref 12",
  "alien browser snapshot",
  "alien browser snapshot --format aria --limit 200",
  "alien browser snapshot --efficient",
  "alien browser snapshot --labels",
];

export const browserActionExamples = [
  "alien browser navigate https://example.com",
  "alien browser resize 1280 720",
  "alien browser click 12 --double",
  "alien browser click-coords 120 340",
  'alien browser type 23 "hello" --submit',
  "alien browser press Enter",
  "alien browser hover 44",
  "alien browser drag 10 11",
  "alien browser select 9 OptionA OptionB",
  "alien browser upload /tmp/alien/uploads/file.pdf",
  'alien browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "alien browser dialog --accept",
  'alien browser wait --text "Done"',
  "alien browser evaluate --fn '(el) => el.textContent' --ref 7",
  "alien browser console --level error",
  "alien browser pdf",
];
